### ISSUE TITLE
Update of example in GWT Boot for RxGWT

### ISSUE THREAD

**Issue by lofidewanto** [intendia-oss/rxgwt#8]
Hi I need a bit support on RxGWT... 😅

I'm updating GWT Boot with the newest version of libs and GWT 2.10.

As I understand it correctly - hope so - RxGWT is completely different now... I have this example:
https://github.com/gwtboot/gwt-boot-samples/tree/master/gwt-boot-sample-rxgwt

I'm bit lost with the dependencies... Do I still need a special version of Elemento like before? Where can I find a current example for RxGWT? Here? https://github.com/intendia-oss/rxgwt/tree/2.x/examples/elemental2

Is the example https://github.com/gwtboot/gwt-boot-samples/tree/master/gwt-boot-sample-rxgwt still up-to-date?

Should I exchange the example just like the project above?

Questions over questions...

Thanks a lot!

**Comment by lofidewanto** [comment]
Hi @ibaca,

thanks a lot for your PR. I merged it and it seems to compile and the example works.

A question though...

This is the starter module for RxGWT: https://github.com/gwtboot/gwt-boot-modules/blob/master/gwt-boot-starters/gwt-boot-starter-rxgwt/pom.xml

Do I still need a special version of Elemento Core in this version:

`
<elemento-core.version>1.0.10-gwtcom</elemento-core.version>
`

for this version of RxGWT?

`
<rx-java-gwt.version>2.2.20-gwt1</rx-java-gwt.version>
`

Thanks!

**Comment by ibaca** [comment]
RxGWT should work with both elemento variants. But, gwt-boot-starters has an explicit dependency with gwt-user, and the unique advantage on changing elemento-core 1.0.10-gwtcon to 1.0.10 is to avoid that dependency. So... you should remove it from gwt-boot-starters too if you want to truly remove the gwt-user dependency. But anyway, yes... you can remove gwtcom and it'll compile.

**Comment by lofidewanto** [comment]
OK, thanks a lot!
